DROP TABLE IF EXISTS SYS_ROLE_RESOURCE_ITEM;
CREATE TABLE `SYS_ROLE_RESOURCE_ITEM`(
    `RSI_ID` bigint AUTO_INCREMENT COMMENT '表ID，主键，供其他表做外键',
    `ROLE_ID` bigint COMMENT '角色ID',
    `RESOURCE_ITEM_ID` bigint COMMENT '功能控件ID',
    `OBJECT_VERSION_NUMBER` decimal(20,0) DEFAULT 1     ,
    `REQUEST_ID` bigint DEFAULT -1    ,
    `PROGRAM_ID` bigint DEFAULT -1    ,
    `CREATION_DATE` datetime DEFAULT now() ,
    `CREATED_BY` decimal(20,0) DEFAULT -1    ,
    `LAST_UPDATED_BY` decimal(20,0) DEFAULT -1    ,
    `LAST_UPDATE_DATE` datetime DEFAULT now() ,
    `LAST_UPDATE_LOGIN` decimal(20,0),
    `ATTRIBUTE_CATEGORY` varchar(30),
    `ATTRIBUTE1` varchar(240),
    `ATTRIBUTE2` varchar(240),
    `ATTRIBUTE3` varchar(240),
    `ATTRIBUTE4` varchar(240),
    `ATTRIBUTE5` varchar(240),
    `ATTRIBUTE6` varchar(240),
    `ATTRIBUTE7` varchar(240),
    `ATTRIBUTE8` varchar(240),
    `ATTRIBUTE9` varchar(240),
    `ATTRIBUTE10` varchar(240),
    `ATTRIBUTE11` varchar(240),
    `ATTRIBUTE12` varchar(240),
    `ATTRIBUTE13` varchar(240),
    `ATTRIBUTE14` varchar(240),
    `ATTRIBUTE15` varchar(240),
    PRIMARY KEY(`RSI_ID`),
    KEY `SYS_ROLE_RESOURCE_ITEM_N1`(`ROLE_ID`),
    UNIQUE KEY `SYS_ROLE_RESOURCE_ITEM_U1`(`ROLE_ID`,`RESOURCE_ITEM_ID`)
) COMMENT = '角色功能控件表，用于对控件控制';
