DROP TABLE IF EXISTS SYS_FUNCTION_RESOURCE;
CREATE TABLE `SYS_FUNCTION_RESOURCE`(
    `FUNC_SRC_ID` bigint AUTO_INCREMENT COMMENT '表ID，主键，供其他表做外键',
    `FUNCTION_ID` bigint COMMENT '外键，功能 ID',
    `RESOURCE_ID` bigint,
    `OBJECT_VERSION_NUMBER` decimal(20,0) DEFAULT 1     ,
    `REQUEST_ID` bigint DEFAULT -1 COMMENT '外键，资源 ID',
    `PROGRAM_ID` bigint DEFAULT -1,
    `CREATION_DATE` datetime DEFAULT now() ,
    `CREATED_BY` decimal(20,0) DEFAULT -1    ,
    `LAST_UPDATED_BY` decimal(20,0) DEFAULT -1    ,
    `LAST_UPDATE_DATE` datetime DEFAULT now() ,
    `LAST_UPDATE_LOGIN` decimal(20,0),
    `ATTRIBUTE_CATEGORY` varchar(30),
    `ATTRIBUTE1` varchar(240),
    `ATTRIBUTE2` varchar(240),
    `ATTRIBUTE3` varchar(240),
    `ATTRIBUTE4` varchar(240),
    `ATTRIBUTE5` varchar(240),
    `ATTRIBUTE6` varchar(240),
    `ATTRIBUTE7` varchar(240),
    `ATTRIBUTE8` varchar(240),
    `ATTRIBUTE9` varchar(240),
    `ATTRIBUTE10` varchar(240),
    `ATTRIBUTE11` varchar(240),
    `ATTRIBUTE12` varchar(240),
    `ATTRIBUTE13` varchar(240),
    `ATTRIBUTE14` varchar(240),
    `ATTRIBUTE15` varchar(240),
    PRIMARY KEY(`FUNC_SRC_ID`),
    UNIQUE KEY `SYS_FUNCTION_RESOURCE_U1`(`FUNCTION_ID`,`RESOURCE_ID`)
) COMMENT = '功能资源关联表';
